"""Adds zip code

Revision ID: 4b7330ab2139
Revises: 3f1e69d3cf0d
Create Date: 2018-05-08 18:57:17.771155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b7330ab2139'
down_revision = '3f1e69d3cf0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('zip', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_zip'), 'user', ['zip'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_zip'), table_name='user')
    op.drop_column('user', 'zip')
    # ### end Alembic commands ###
